# This file provides instructions for packaging.

`MooseX-ArrayRef`
	perl_version_from m`MooseX::ArrayRef`;
	version_from      m`MooseX::ArrayRef`;
	readme_from       m`MooseX::ArrayRef`;
	requires          m`Moose 2.00`;
	test_requires     p`Test::More 0.61`  .

